// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: order/grpc.proto

package grpcTaxiOrder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InnoTaxiOrderClient is the client API for InnoTaxiOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InnoTaxiOrderClient interface {
	RateOrderByUser(ctx context.Context, in *OrderRate, opts ...grpc.CallOption) (*OrderUserSide, error)
	GetAllUserOrders(ctx context.Context, in *Email, opts ...grpc.CallOption) (*UserOrders, error)
	OrderTaxi(ctx context.Context, in *RequestTaxi, opts ...grpc.CallOption) (*TaxiResponse, error)
	RateOrderByDriver(ctx context.Context, in *OrderRate, opts ...grpc.CallOption) (*OrderDriverSide, error)
	GetAllDriverOrders(ctx context.Context, in *Email, opts ...grpc.CallOption) (*DriverOrders, error)
	EndOrder(ctx context.Context, in *Email, opts ...grpc.CallOption) (*OrderDriverSide, error)
}

type innoTaxiOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewInnoTaxiOrderClient(cc grpc.ClientConnInterface) InnoTaxiOrderClient {
	return &innoTaxiOrderClient{cc}
}

func (c *innoTaxiOrderClient) RateOrderByUser(ctx context.Context, in *OrderRate, opts ...grpc.CallOption) (*OrderUserSide, error) {
	out := new(OrderUserSide)
	err := c.cc.Invoke(ctx, "/grpcTaxiOrderSchema.InnoTaxiOrder/RateOrderByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *innoTaxiOrderClient) GetAllUserOrders(ctx context.Context, in *Email, opts ...grpc.CallOption) (*UserOrders, error) {
	out := new(UserOrders)
	err := c.cc.Invoke(ctx, "/grpcTaxiOrderSchema.InnoTaxiOrder/GetAllUserOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *innoTaxiOrderClient) OrderTaxi(ctx context.Context, in *RequestTaxi, opts ...grpc.CallOption) (*TaxiResponse, error) {
	out := new(TaxiResponse)
	err := c.cc.Invoke(ctx, "/grpcTaxiOrderSchema.InnoTaxiOrder/OrderTaxi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *innoTaxiOrderClient) RateOrderByDriver(ctx context.Context, in *OrderRate, opts ...grpc.CallOption) (*OrderDriverSide, error) {
	out := new(OrderDriverSide)
	err := c.cc.Invoke(ctx, "/grpcTaxiOrderSchema.InnoTaxiOrder/RateOrderByDriver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *innoTaxiOrderClient) GetAllDriverOrders(ctx context.Context, in *Email, opts ...grpc.CallOption) (*DriverOrders, error) {
	out := new(DriverOrders)
	err := c.cc.Invoke(ctx, "/grpcTaxiOrderSchema.InnoTaxiOrder/GetAllDriverOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *innoTaxiOrderClient) EndOrder(ctx context.Context, in *Email, opts ...grpc.CallOption) (*OrderDriverSide, error) {
	out := new(OrderDriverSide)
	err := c.cc.Invoke(ctx, "/grpcTaxiOrderSchema.InnoTaxiOrder/EndOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InnoTaxiOrderServer is the server API for InnoTaxiOrder service.
// All implementations must embed UnimplementedInnoTaxiOrderServer
// for forward compatibility
type InnoTaxiOrderServer interface {
	RateOrderByUser(context.Context, *OrderRate) (*OrderUserSide, error)
	GetAllUserOrders(context.Context, *Email) (*UserOrders, error)
	OrderTaxi(context.Context, *RequestTaxi) (*TaxiResponse, error)
	RateOrderByDriver(context.Context, *OrderRate) (*OrderDriverSide, error)
	GetAllDriverOrders(context.Context, *Email) (*DriverOrders, error)
	EndOrder(context.Context, *Email) (*OrderDriverSide, error)
	mustEmbedUnimplementedInnoTaxiOrderServer()
}

// UnimplementedInnoTaxiOrderServer must be embedded to have forward compatible implementations.
type UnimplementedInnoTaxiOrderServer struct {
}

func (UnimplementedInnoTaxiOrderServer) RateOrderByUser(context.Context, *OrderRate) (*OrderUserSide, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateOrderByUser not implemented")
}
func (UnimplementedInnoTaxiOrderServer) GetAllUserOrders(context.Context, *Email) (*UserOrders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllUserOrders not implemented")
}
func (UnimplementedInnoTaxiOrderServer) OrderTaxi(context.Context, *RequestTaxi) (*TaxiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderTaxi not implemented")
}
func (UnimplementedInnoTaxiOrderServer) RateOrderByDriver(context.Context, *OrderRate) (*OrderDriverSide, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateOrderByDriver not implemented")
}
func (UnimplementedInnoTaxiOrderServer) GetAllDriverOrders(context.Context, *Email) (*DriverOrders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllDriverOrders not implemented")
}
func (UnimplementedInnoTaxiOrderServer) EndOrder(context.Context, *Email) (*OrderDriverSide, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndOrder not implemented")
}
func (UnimplementedInnoTaxiOrderServer) mustEmbedUnimplementedInnoTaxiOrderServer() {}

// UnsafeInnoTaxiOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InnoTaxiOrderServer will
// result in compilation errors.
type UnsafeInnoTaxiOrderServer interface {
	mustEmbedUnimplementedInnoTaxiOrderServer()
}

func RegisterInnoTaxiOrderServer(s grpc.ServiceRegistrar, srv InnoTaxiOrderServer) {
	s.RegisterService(&InnoTaxiOrder_ServiceDesc, srv)
}

func _InnoTaxiOrder_RateOrderByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnoTaxiOrderServer).RateOrderByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcTaxiOrderSchema.InnoTaxiOrder/RateOrderByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnoTaxiOrderServer).RateOrderByUser(ctx, req.(*OrderRate))
	}
	return interceptor(ctx, in, info, handler)
}

func _InnoTaxiOrder_GetAllUserOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Email)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnoTaxiOrderServer).GetAllUserOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcTaxiOrderSchema.InnoTaxiOrder/GetAllUserOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnoTaxiOrderServer).GetAllUserOrders(ctx, req.(*Email))
	}
	return interceptor(ctx, in, info, handler)
}

func _InnoTaxiOrder_OrderTaxi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTaxi)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnoTaxiOrderServer).OrderTaxi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcTaxiOrderSchema.InnoTaxiOrder/OrderTaxi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnoTaxiOrderServer).OrderTaxi(ctx, req.(*RequestTaxi))
	}
	return interceptor(ctx, in, info, handler)
}

func _InnoTaxiOrder_RateOrderByDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnoTaxiOrderServer).RateOrderByDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcTaxiOrderSchema.InnoTaxiOrder/RateOrderByDriver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnoTaxiOrderServer).RateOrderByDriver(ctx, req.(*OrderRate))
	}
	return interceptor(ctx, in, info, handler)
}

func _InnoTaxiOrder_GetAllDriverOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Email)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnoTaxiOrderServer).GetAllDriverOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcTaxiOrderSchema.InnoTaxiOrder/GetAllDriverOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnoTaxiOrderServer).GetAllDriverOrders(ctx, req.(*Email))
	}
	return interceptor(ctx, in, info, handler)
}

func _InnoTaxiOrder_EndOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Email)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnoTaxiOrderServer).EndOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcTaxiOrderSchema.InnoTaxiOrder/EndOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnoTaxiOrderServer).EndOrder(ctx, req.(*Email))
	}
	return interceptor(ctx, in, info, handler)
}

// InnoTaxiOrder_ServiceDesc is the grpc.ServiceDesc for InnoTaxiOrder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InnoTaxiOrder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcTaxiOrderSchema.InnoTaxiOrder",
	HandlerType: (*InnoTaxiOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RateOrderByUser",
			Handler:    _InnoTaxiOrder_RateOrderByUser_Handler,
		},
		{
			MethodName: "GetAllUserOrders",
			Handler:    _InnoTaxiOrder_GetAllUserOrders_Handler,
		},
		{
			MethodName: "OrderTaxi",
			Handler:    _InnoTaxiOrder_OrderTaxi_Handler,
		},
		{
			MethodName: "RateOrderByDriver",
			Handler:    _InnoTaxiOrder_RateOrderByDriver_Handler,
		},
		{
			MethodName: "GetAllDriverOrders",
			Handler:    _InnoTaxiOrder_GetAllDriverOrders_Handler,
		},
		{
			MethodName: "EndOrder",
			Handler:    _InnoTaxiOrder_EndOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/grpc.proto",
}
